FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN DATABASE_URL="mysql://user:password@localhost:3306/mydb" npx prisma generate
EXPOSE 5175
CMD ["node", "-r", "tsx/cjs", "index.js"]